# Generated by Django 5.1.1 on 2024-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correction',
            field=models.TextField(default=''),
        ),
    ]
