# Generated by Django 5.1.1 on 2024-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_question_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
