# Generated by Django 5.1.1 on 2024-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_alter_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Question ', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Question Texte'), ('python', 'Question Code Python'), ('nodejs', 'Question Code NodeJs'), ('sql', 'Question Code Sql'), ('qcm', 'Question à Choix Multiple')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
