# Generated by Django 5.1.1 on 2024-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_question_already_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='already_done',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='already_done',
            field=models.BooleanField(default=False),
        ),
    ]
