# Generated by Django 5.1.1 on 2024-09-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_alter_question_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
