# Generated by Django 5.1.1 on 2024-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_alter_userresponse_id_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='tme_left',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
