# Generated by Django 5.1.1 on 2024-10-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_appuser_tme_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='tme_left',
            new_name='time_left',
        ),
    ]
