# Generated by Django 5.1.1 on 2024-10-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_appuser_end_date_appuser_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='time_taken',
        ),
    ]
