# Generated by Django 5.1.1 on 2024-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_remove_userresponse_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.PositiveIntegerField(default=0, unique=True)),
                ('minutes', models.PositiveIntegerField(default=0, unique=True)),
                ('seconds', models.PositiveIntegerField(default=0, unique=True)),
            ],
        ),
    ]
