# Generated by Django 5.1.1 on 2024-10-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0016_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='multiple_choice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
