# Generated by Django 5.1.1 on 2024-10-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0017_userresponse_multiple_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='multiple_choice',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='choices',
            field=models.ManyToManyField(blank=True, to='skill.choice'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='note',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
