# Generated by Django 5.1.1 on 2024-10-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0018_remove_userresponse_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
