# Generated by Django 5.1.1 on 2024-10-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0019_alter_choice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='note',
            new_name='note_qcm',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='note_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
